name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache .m2 repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build
        run: ./mvnw -B package -Pcli
      - name: Generate Java wrapper
        run: ./generate-java-wrapper.sh
      - name: Test
        run: ./mvnw -B clean verify
      - name: Check for generator results
        run: |
          git status --porcelain
          git diff --exit-code
